name: PlaywrightSauceDemo tests execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright
        shell: pwsh
        run: .\Tests\bin\Release\net8.0\playwright.ps1 install --with-deps

      - name: Run Tests
        run: dotnet test 

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Tests/bin/Release/net8.0/TestResults
          retention-days: 7
